girder/covalic

server/models/submission.py
server/rest/submission.py
web_external/js/models/SubmissionModel.js
web_external/js/views/body/SubmitView.js
web_external/stylesheets/submissionPage.styl
web_external/stylesheets/submitPage.styl
web_external/templates/body/phasePage.jade
web_external/templates/body/submissionPage.jade
web_external/templates/body/submitPage.jade
web_external/templates/widgets/leaderboard.jade

Users are required to enter it when submitting. It is displayed
in the leader board.

Add a title to the submission.

---

ansible/roles/girder/tasks/main.yml
ansible/update_girder.sh

Adding a script to run an update.

---

ansible/roles/celery/tasks/main.yml
worker.dist.cfg
worker/score.py

Merging this so I can test out a change to celery code.

Support docker container run command for scoring metrics

---

server/models/submission.py
server/rest/phase.py
web_external/templates/body/scoringMetrics.jade

When metric IDs or weights change for a phase, recompute all scores

---

web_external/js/views/body/ChallengeView.js
web_external/js/views/body/ChallengesView.js
web_external/js/views/body/PhaseView.js
web_external/js/views/body/SubmissionView.js
web_external/js/views/layout/HeaderUserView.js

Fixes regression introduced by 41d1b90
This will restore the well functioning of these actions:
* Creating a new challenge redirects to the challenge page
* Deleting a challenge redirects to the challenges list
* Searching challenge
* Deleting a phase redirect to the challenge page
* Submission failure redirects to the challenges list
* Clicking on user setting

Fixes #87. Ensure routing works as expected using "covalic.router"

---

ansible/roles/girder/tasks/main.yml
ansible/roles/girder/templates/nginx.j2
ansible/roles/girder/templates/nginx_prod.j2

See http://stackoverflow.com/a/13673298/2550451

Better SSE proxy support

---

server/__init__.py

Make COVALIC app load js/css from all enabled plugins dynamically

---

web_external/templates/body/challengeLearn.jade

Update documentation to refer to Resonant.

TangeloHub -> Resonant

---

ansible/ansible.cfg

https://github.com/ansible/ansible/issues/11536

Fix cryptic ansible error

---

server/__init__.py
web_external/js/views/body/NewChallengeView.js
web_external/js/views/body/NewPhaseView.js
web_external/js/views/widgets/EditChallengeWidget.js
web_external/js/views/widgets/EditPhaseWidget.js
web_external/templates/body/newChallengePage.jade
web_external/templates/body/newPhasePage.jade
web_external/templates/widgets/editChallengeWidget.jade
web_external/templates/widgets/editPhaseWidget.jade

Depends on https://github.com/girder/girder/pull/1112

Allow setting and editing challenge/phase timeframes

---

ansible/library/girder.py
ansible/provision.yml
ansible/roles/girder/tasks/main.yml

This works for the vagrant install, but I still need to make it work for the AWS deployment.

Use the girder ansible module for vagrant mode

---

web_external/js/views/body/ChallengesView.js
web_external/templates/body/challengeList.jade

This connects the challenge filter dropdown.
Depends on https://github.com/girder/challenge/pull/37.

Add support to filter challenges by timeframe

---

server/__init__.py
web_external/js/views/body/ChallengesView.js
web_external/stylesheets/body/challengeList.styl

Depends on https://github.com/girder/girder/pull/1146

Use new core search features

---

server/rest/submission.py
web_external/js/views/body/NewPhaseView.js
web_external/js/views/body/PhaseView.js
web_external/js/views/body/SubmissionView.js
web_external/js/views/widgets/EditPhaseWidget.js
web_external/templates/body/newPhasePage.jade
web_external/templates/widgets/editPhaseWidget.jade

Implement hidden scores for participants as an option on phases

---

server/__init__.py
server/rest/phase.py
server/rest/submission.py
web_external/js/views/body/NewPhaseView.js
web_external/js/views/body/PhaseView.js
web_external/js/views/body/SubmissionView.js
web_external/js/views/widgets/EditPhaseWidget.js
web_external/templates/body/newPhasePage.jade
web_external/templates/body/phasePage.jade
web_external/templates/widgets/editPhaseWidget.jade

Scoring container editing

---

ansible/roles/celery/tasks/main.yml

Also add new system packages required by PIL to celery nodes.
ping @brianhelba @msmolens

Install docker on celery nodes in modern way

---

web_external/js/views/widgets/ScoreDetailWidget.js
web_external/js/views/widgets/SubmissionListWidget.js
web_external/stylesheets/body/submissionPage.styl
web_external/stylesheets/widgets/leaderboard.styl
web_external/templates/widgets/leaderboard.jade
web_external/templates/widgets/scoreDetails.jade

- add arrow icon to indicate that submission details are available by clicking score
- show more date details
- fix link to user
Leaderboard table:
Submission detail table:

Tweak leaderboard UI

---

server/__init__.py
server/models/submission.py

Ensure that the creator name field in the submission model is updated if the
user's name changes.
Fixes #187

Keep submission creator names up-to-date

---

server/rest/submission.py
web_external/js/views/body/SubmissionView.js
web_external/js/views/widgets/ScoreDetailWidget.js
web_external/js/views/widgets/SubmissionListWidget.js
web_external/templates/body/submissionPage.jade
web_external/templates/widgets/leaderboard.jade
web_external/templates/widgets/scoreDetails.jade

Otherwise we cannot legally encode them as JSON

Coerce nan or infinite scores to strings

---

ansible/roles/celery/templates/worker.local.cfg.j2
server/rest/submission.py

Use girder_io plugin to fetch files instead of direct http

---

server/rest/submission.py

Use format=text for inputs

---

ansible/group_vars/all
ansible/roles/girder/tasks/main.yml

Fix vagrant provisioning

---

server/rest/submission.py

This allows a sparse scoring matrix to be submitted.

Allow null score values

---

web_external/stylesheets/body/submissionPage.styl
web_external/templates/widgets/scoreDetails.pug
web_external/views/widgets/ScoreDetailWidget.js

- Display full metric name in score detail table.
- Add note that score column headers are clickable.
- Fix popover positioning bug with wide tables.

Display full metric name in score detail table

---

server/rest/submission.py

This permits site admins to correct any issues with metadata, without requiring a participant to make a new submission.

Add a new endpoint, allowing site admins to update some submission metadata

---

server/rest/submission.py

Validate the score output by the scoring container and posted by the
scoring robot according to a JSON schema. This should provide
informative error messages if a scoring container outputs invalid JSON.

Validate scores using JSON schema

---

Vagrantfile
ansible/roles/celery/tasks/main.yml
ansible/roles/common/tasks/main.yml
ansible/roles/girder/tasks/main.yml
ansible/roles/mongodb/tasks/main.yml
ansible/roles/mq/tasks/main.yml
ansible/roles/vagrant/tasks/main.yml
ansible/vagrant.yml

* Upgrade base box to xenial
* Upgrade node to version 8
* Rename sudo: to become:

Fix covalic vagrant deployment for latest ansible

---

web_external/stylesheets/body/frontPage.styl
web_external/templates/body/frontPage.pug

@mgrauer @jeffbaumes @jbeezley @msmolens

Privacy notice on front page

---

plugin_tests/phase_test.py
server/models/phase.py
server/rest/phase.py

This is a similar change to #245, but here I didn't update to `autoDescribeRoute` because it would have required changing too much unrelated code.

Add a json metadata field to the phase model

---

plugin_tests/phase_test.py
plugin_tests/submission_test.py
server/__init__.py
server/models/submission.py
server/rest/phase.py
server/rest/submission.py

- Add endpoint to re-score a specific submission
- Add endpoint to re-score the latest submissions in a phase

Allow re-scoring submissions

---

covalic/__init__.py
covalic/rest/submission.py

This incorporates the upstream changes from https://github.com/girder/girder/pull/3103 .

Use refactored mail_utils from upstream Girder
