girder/covalic

web_external/js/views/body/SubmissionView.js
web_external/stylesheets/body/submissionPage.styl
web_external/templates/widgets/submissionError.jade

This creates a new submission with the same properties as the old one.  In the future this may need to be protected by access control if we don't want end users to be able to do it.  For now, this is useful for development/debugging.

Rerun a submission in error.  Fixes #69.

---

server/__init__.py

This commit fixes a regression introduced by girder/girder@f34130b (Make
all PyMongo "find" queries not timeout).

Fixes #88. Restore proper functioning of phase deletion.

---

web_external/js/views/body/SubmissionView.js

When a job was in progress and the submission view was shown, it
sometimes did not automatically update when the job status changed.

Attempt to fix race condition on submission processing view

---

ansible/roles/girder/templates/nginx_prod.j2

This instructs browsers to always attempt to use https to access this domain.
@mgrauer PTAL, I already deployed this onto challenge.kitware.com and it seems to be working.

Use Strict-Transport-Security header

---

ansible/roles/celery/tasks/main.yml

Running "vagrant up" failed with an error when running the "Restart
Docker Daemon" task because the name of the docker service was
incorrect. This commit corrects the name of the service.

Fix ansible Restart Docker Daemon task

---

server/rest/submission.py

This commit fixes the following warning when starting Girder:
WARNING: Resource subclass "Submission" did not call "Resource__init__()" from its constructor.

Fix Submission startup warning

---

server/rest/phase.py
web_external/js/models/PhaseModel.js
web_external/js/views/body/PhaseInputView.js
web_external/js/views/body/PhaseView.js

For groundtruth or input folders of phases that contain only
a single item, we download just the item rather than the folder
containing it, to avoid an unnecessary zip file.
ping @brianhelba this is the fastest and simplest workaround I could come up with for your particular case. Hopefully it's good enough to also be the general solution.

Refs #37. Special handling of single-item dataset downloads

---

.travis.yml

node-gyp requires python 2. Installing the latest version of
npm avoids this issue entirely.

Fix travis on python 3

---

web_external/js/.jshintrc
web_external/js/views/body/ChallengePhasesView.js
web_external/js/views/body/ChallengeTimelineView.js
web_external/js/views/body/ChallengeView.js
web_external/stylesheets/body/challengePage.styl
web_external/stylesheets/body/challengeTimelinePage.styl
web_external/templates/body/challengePage.jade

This is a first cut at adding a TimelineWidget to represent the schedule of a challenge:
Phase start/end dates appear as points. Details are in the tooltips.
Overall progress is represented using segments.

Challenge timeline widget

---

web_external/js/views/body/ChallengesView.js
web_external/templates/body/challengeList.jade

Previously if you selected a filter on the list of challenges, clicked through to a challenge, then went back in your browser, the filter would reset to the default. Now the selected filter is maintained through that workflow.

Challenge timeframe routing

---

web_external/js/views/body/NewPhaseView.js
web_external/js/views/widgets/EditPhaseWidget.js
web_external/stylesheets/body/phasePage.styl
web_external/templates/body/newPhasePage.jade
web_external/templates/body/phasePage.jade
web_external/templates/widgets/editPhaseWidget.jade

This adds an option to classify a phase as a 'training' phase. The user
interface is a simple checkbox ('Training phase').
Currently the only visible effect is to set the label of the button which
downloads the phase's dataset.
Depends on https://github.com/girder/challenge/pull/41
Fixes #150

Distinguish training phases

---

server/__init__.py

This updates the references to Girder's libraries in the web root.
This fixes broken styling due to the reference to ext.min.css, which was
short-lived in the Girder repository and therefore doesn't have a compatibility
symlink.

Update stylesheet and script paths in web root

---

web_external/js/views/body/NewPhaseView.js
web_external/js/views/body/SubmitView.js
web_external/js/views/widgets/EditPhaseWidget.js
web_external/stylesheets/body/phasePage.styl
web_external/templates/body/newPhasePage.jade
web_external/templates/body/submitPage.jade
web_external/templates/widgets/editPhaseWidget.jade

This commit adds user interface elements for and uses the phase match submission
field. When `matchSubmissions` is true, submission filenames must match ground
truth filenames one-to-one. When `matchSubmissions` is false, any filenames are
accepted.
Depends on https://github.com/girder/challenge/pull/45

Use phase match submissions field

---

server/scoring.py
web_external/js/views/widgets/ScoreDetailWidget.js

This permits a sparse scoring matrix to be created, where the missing values do not affect the average score for a given metric type.

Allow score metric values to be null

---

server/__init__.py
server/constants.py
server/mail_templates/covalic.submissionCompleteAdmin.mako
server/mail_templates/covalic.submissionErrorAdmin.mako
server/mail_templates/covalic.submissionErrorUser.mako

Include error logs when sending email notifications of a submission error. The
admin email includes the full error log and the user email includes a minimal
error log. The minimal error log contains the specific error from the scoring
container to help the user fix their submission.
Additionally, the admin email template for a successful submission is updated
for consistency with the error template with respect to the included user
information.
Fixes #168

Include error logs in email

---

.travis.yml
plugin.cmake
plugin_tests/user_emails_test.py
server/__init__.py
server/mail_templates/covalic.submissionErrorAdmin.mako
server/rest/submission.py
server/utility/user_emails.py

Previously, email notifications of successful submissions and submission errors
were sent to site admins. This change sends the notifications to challenge/phase
admins instead. In this context, an admin is a user with WRITE access or above
on the challenge or phase.
Email notifications to the user remain unchanged.
Fixes #162

Send email notifications to challenge/phase admins instead of site admins

---

web_external/js/views/body/PhaseView.js
web_external/templates/body/submissionPage.jade

When hiding scores:
- Hide 'Leaderboard' header on phase page
- Replace 'View leaderboard' text on button that returns to phase after submitting
Fixes #175

Hide leaderboard references when hiding scores

---

web_external/js/collections/SubmissionCollection.js

This overrides the default `girder.Collection` sort options for a
`SubmissionCollection`. By default, a `girder.Collection` is sorted by the 'name'
parameter, which does not exist for submissions.

Fix sorting by overall score on leaderboard

---

server/models/submission.py
server/rest/submission.py

The POST submission endpoint now accepts two optional parameters, both of which
require site admin access:
- date: override the submission creation date.
- userId: the user to submit on behalf of.
This enables admins to add a user's submission to the system when the user was
unable to do so themselves.

Allow site admins to submit on behalf of users

---

server/models/submission.py
server/rest/submission.py

Exclude the score field from submissions when listing all submissions. This
change makes listing submissions more scalable with a large number of
submissions or many score metrics.
The score field remains accessible when requesting a submission directly by its
ID.

Exclude score field when listing all submissions

---

utils/rescore_phase.py

Add a script to re-run the scoring algorithm on previously submitted entries to a challenge phase.
This might be sufficient for #183 in the short term.
In the long term, it would be nice to integrate re-running the scoring algorithm, along with other operations, into the submission dashboard (#186).

Add utility script to rescore a phase

---

ansible/roles/girder/tasks/main.yml
ansible/roles/mongodb/tasks/main.yml
ansible/roles/mongodb/templates/backup_db.sh
ansible/roles/mongodb/templates/upload_to_s3.py
ansible/usage.md
ansible/utils/provision.sh

@mgrauer this is the backup script for now, it's installed on the mongo machine via ansible for cost savings. It uses timestamped key names so we don't overwrite old backups, but for now we'll need to manually manage the backup process and cleaning out old backups.

Backup script for mongodb

---

ansible/group_vars/all
ansible/roles/mongodb/tasks/main.yml
ansible/usage.md
ansible/vagrant.yml

This coincides with changing the mongodb prod instance to a
more powerful machine with a much larger volume. The new
machine is also under a special IAM role so that it does not
require credentials to write into the backup bucket.
ping @mgrauer

Keep mongo database on its own volume

---

web_external/js/views/body/ChallengePhasesView.js
web_external/templates/body/challengePhasesPage.jade

Previously, links to phases on the challenge page used an event handler that
calls router.navigate().
Now, links to phases use an href. This allows actions like opening phases in new
tabs and copying the link URL.

Use href for phase links

---

plugin.cmake
plugin_tests/submission_folder_access_test.py
server/__init__.py
server/models/submission.py

Phase admins are granted read permission on submission folders.
Submission folder permissions are updated if a phase's access control changes.
Fixes #195

Allow phase admins to read submission folders

---

web_external/js/models/SubmissionModel.js
web_external/js/views/body/PhaseSubmissionsView.js
web_external/js/views/body/UserSubmissionsView.js
web_external/stylesheets/body/phaseSubmissionsPage.styl
web_external/stylesheets/body/userSubmissionsPage.styl
web_external/templates/body/phasePage.jade
web_external/templates/body/phaseSubmissionsPage.jade
web_external/templates/body/userSubmissionsPage.jade

This adds an administrator interface to view all submissions to a phase. A
button at the bottom of the phase page routes to this interface.
Currently, the view shows submissions grouped by participant. By default,
submissions for up to five participants are shown at a time. The controls at the
top of the interface page through the list. The 'participantLimit' query
parameter sets the number of participants per page.
By default, up to five submissions per participant are shown at a time. The
controls in the group for each user page through the list. The 'submissionLimit'
query parameter sets the number of submissions to show per page.
Each submission shows its title, whether it's the latest successful submission,
its job status, its creation date, and its overall score. The job status text …

Add basic submission dashboard

---

web_external/js/views/body/SubmissionView.js
web_external/stylesheets/body/submissionPage.styl
web_external/templates/body/submissionPage.jade

This commit adds a button on the submission detail page to download the
submission data. The button is visible to phase admins. If a submission folder
contains only one item, then the item is downloaded directly. Otherwise, the
folder is downloaded as a zip file.
Fixes #198

Allow downloading submission data

---

web_external/templates/body/userSubmissionsPage.jade

This commit adds a direct link back to the submission view. When a submission is
successful, this provides a shortcut to view the score details without
navigating back to the leaderboard. When a submission fails, this makes it
easier to restart the submission from the submission view.
Fixes #201

On submission dashboard, add link to submission

---

web_external/js/views/body/NewChallengeView.js
web_external/js/views/body/NewPhaseView.js
web_external/stylesheets/body/challengePage.styl
web_external/templates/body/challengePhasesPage.jade

cc: @brianhelba 
Screenshot:
Currently this displays the description in its entirety. We had discussed truncating it, but I'm not sure that's necessary.
Fixes #209

Display phase descriptions on challenge overview page

---

server/__init__.py

Fix a problem where the job log emails don't include the submission job
log. The emails erroneously stated that "No log is available."
The first problem is that the log sent in the `jobs.job.update` event is
no longer necessarily up-to-date, and may be empty. According to the
documentation [1], the job document should be manually re-refetched to
get the complete log.
The second problem is that the log is now a list, and the list elements
aren't necessarily broken at newlines. To fix this, we join the list
into a string before processing it.
[1] http://girder.readthedocs.io/en/latest/plugins.html

Fix job log emails

---

web_external/templates/body/phasePage.pug

Fix a regression where several items on the phase page menu are misaligned. This first regressed in https://github.com/girder/covalic/commit/e28bed2ac9b6da0818699408c4e7c855e048c38f.

Fix phase page menu item spacing

---

plugin_tests/phase_test.py
server/models/phase.py
server/models/submission.py
server/rest/phase.py
server/rest/submission.py
web_external/models/SubmissionModel.js
web_external/router.js
web_external/stylesheets/body/phasePage.styl
web_external/stylesheets/body/submitPage.styl
web_external/stylesheets/body/userSubmissionsPage.styl
web_external/templates/body/newPhasePage.pug
web_external/templates/body/phaseConfigureSubmissionsPage.pug
web_external/templates/body/phasePage.pug
web_external/templates/body/submitPage.pug
web_external/templates/body/userSubmissionsPage.pug
web_external/templates/widgets/editPhaseWidget.pug
web_external/templates/widgets/leaderboard.pug
web_external/views/body/NewPhaseView.js
web_external/views/body/PhaseConfigureSubmissionsView.js
web_external/views/body/PhaseGroundTruthView.js
web_external/views/body/SubmissionView.js
web_external/views/body/SubmitView.js
web_external/views/body/UserSubmissionsView.js
web_external/views/widgets/EditPhaseWidget.js

This allows entering more metadata about a submission. Now, instead of supplying only a title along with a submission, the phase can be configured to additionally require any of the following pre-defined fields:
- Organization
- Organization URL
- Documentation URL
Some of this information is displayed in the leaderboard, but currently it's conservative in that the URLs are visible only to phase admins.
This fixes https://github.com/girder/covalic/issues/182 (somewhat) and should address the immediate needs of the 2017 ISIC Challenge.

Add optional submission fields

---

web_external/stylesheets/body/challengePage.styl

COVALIC build broke against the latest version of Girder master since it moved to the latest version of webpack (2.2.0). There's a problem where stylus does not properly resolve relative imports. I tried to fix it in Girder itself, but I haven't found any simple way to fix it yet. To get us working against latest master for the moment, I've just removed the relative import for now.
@msmolens PTAL

Workaround broken relative imports in webpack 2.2 for stylus

---

server/__init__.py

This fixes missing girder symbols when loading the web front-end.

Include girder_app.js

---

plugin_tests/phase_test.py
server/models/phase.py
server/rest/phase.py
server/rest/submission.py
web_external/models/PhaseModel.js
web_external/templates/body/phaseConfigureSubmissionsPage.pug
web_external/templates/body/submitPage.pug
web_external/templates/body/userSubmissionsPage.pug
web_external/templates/widgets/leaderboard.pug
web_external/views/body/PhaseConfigureSubmissionsView.js
web_external/views/body/SubmitView.js

The following submission fields gain an option to control whether or not
they are required (when enabled):
- enableOrganization
- enableOrganizationUrl
- enableDocumentationUrl
For backwards compatibility, the 'required' options are enabled by
default.
A TODO note is left in the Configure Submissions view about possible
future improvements to the user interface.

Add phase options to make submission fields optional

---

server/rest/submission.py

Add a parameter to the endpoint that updates submission metadata to
enable disqualifying a submission. A disqualified submission will no
longer appear in the leaderboard.

Enable disqualifying a submission

---

web_external/templates/widgets/leaderboard.pug

This changes the leaderboard to show and hyperlink the organization and
documentation fields when available, regardless of whether the user is
a phase admin.
Because the API already returns all these fields, only a front-end
change is necessary here.

Show and hyperlink organization and documentation fields on leaderboard

---

plugin.cmake
plugin_tests/submission_test.py

This is in preparation for the changes I'm about to make to the submission endpoints to support multiple approaches per user to ensure I don't break existing behavior.

Add tests for submission model and endpoints

---

plugin.cmake
plugin_tests/submission_test.py
server/models/submission.py
server/rest/submission.py

This adds the ability for users to submit multiple approaches for each
phase of the challenge.  The approach is stored as a property on the
submission model.  The approach is expected to be an arbitrary string
that is coerced to lower case.
By default, a special approach called "default" is used.  To maintain
backward compatibility with existing databases, the default approach is
stored in the database by the absence of the "approach" key.  The save
and load methods are overridden to handle this behavior at the model
layer.
This also adds a new endpoint to list existing approaches by user and/or
phase.  The list is returned in alphebetical order and "default" is
always injected.
Future work could include adding settings to limit the number of
approaches allowed (even hard code a list of …

Multiple approaches per user

---

plugin.yml
plugin_tests/submission_test.py
server/models/submission.py
server/rest/submission.py
web_external/models/SubmissionModel.js
web_external/templates/body/submissionPage.pug
web_external/templates/body/submitPage.pug
web_external/templates/widgets/leaderboard.pug
web_external/views/body/SubmitView.js

This makes minimal changes to support the ability to submit multiple
approaches per user.
* SubmissionModel: A new method to fetch existing approaches
* SubmitView: Adds a text input (with autocomplete) to set the approach on the model.  This defaults to `default`.
* LeaderboardView: When listing a non-default approach, the approach name is added in parentheses next to the user name.
* SubmissionView: The approach name is added to the details in the subtitle.
Depends on #239.

Add multiple approaches per user in web client

---

server/rest/phase.py

Remove default values from the update phase endpoint description. When using Swagger UI to update a phase, having default values could update some fields inadvertently.

Remove default values from update phase endpoint

---

covalic/web_client/views/ConfigView.js
covalic/web_external/models/ChallengeModel.js
covalic/web_external/models/PhaseModel.js
covalic/web_external/models/SubmissionModel.js

This removes deprecation warnings on the console.

Replace deprecated use of .error on $.ajax calls with .fail

---

covalic/models/submission.py

Rescoring a phase relies on sorting by this field. For larger databases, this sort cannot complete without an index.

Add an index for 'submission.created'
